title: GNU Octave - Packages Documentation
email: webmaster@octave.org
description: >- # this means to ignore newlines until "baseurl:"
  GNU Octave is a programming language for scientific computing.

url: "https://docs.octave.space/package"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
